#!/usr/bin/env python3
"""Write reproducibility records for the two local geometry environments."""
import datetime
import hashlib
import json
import subprocess
from pathlib import Path

root=Path(__file__).resolve().parents[1]
out=root/'setup_logs/geometry_install'
out.mkdir(parents=True,exist_ok=True)
def run(args):
    return subprocess.check_output([str(x) for x in args],cwd=root,text=True).strip()
record={'created_at':datetime.datetime.now().astimezone().isoformat(),'root':str(root),
    'environments':{},'repositories':{},'models':{},'tests':{}}
for name in ['mapanything','game']:
    prefix=root/'conda_envs'/name
    (out/f'{name}_conda_explicit.txt').write_text(run(['/home/sumai/miniconda3/bin/conda','list','-p',prefix,'--explicit'])+'\n')
    (out/f'{name}_pip_freeze.txt').write_text(run([prefix/'bin/python','-m','pip','freeze'])+'\n')
    record['environments'][name]={'prefix':str(prefix),'python':run([prefix/'bin/python','--version']),
        'pip_check':run([prefix/'bin/python','-m','pip','check'])}
for name,path in [('MapAnything',root/'MapAnything'),('GaME',root/'GaME'),
                  ('dinov2',root/'.cache/torch_geometry/hub/facebookresearch_dinov2_main')]:
    record['repositories'][name]={'path':str(path),'commit':run(['git','-C',path,'rev-parse','HEAD']),
        'origin':run(['git','-C',path,'remote','get-url','origin']),
        'worktree_status':run(['git','-C',path,'status','--short'])}
for name in ['mapanything','mapanything-apache']:
    m=json.loads((root/'checkpoints'/name/'local_manifest.json').read_text())
    m.pop('tensor_shapes',None)
    record['models'][name]=m
alex=root/'.cache/torch_geometry/hub/checkpoints/alexnet-owt-7be5be79.pth'
if alex.exists():
    h=hashlib.file_digest(alex.open('rb'),'sha256').hexdigest()
    record['models']['lpips_alexnet']={'path':str(alex),'size_bytes':alex.stat().st_size,'sha256':h}
for path in sorted((root/'geometry_outputs').glob('install_smoke_*/**/report.json')):
    record['tests'][str(path.relative_to(root))]=json.loads(path.read_text())
for path in sorted((root/'setup_logs').glob('*_env_check.json')):
    record['tests'][str(path.relative_to(root))]=json.loads(path.read_text())
deck_dir=root/'presentations/atlas_framework_reproduction_2026-09-06'
deck_record=json.loads((deck_dir/'manifest.json').read_text())
preserved={}
for rel,expected in deck_record['source_svg_sha256'].items():
    actual=hashlib.sha256((root/rel).read_bytes()).hexdigest()
    assert actual==expected, f'Existing SVG changed: {rel}'
    preserved[rel]=actual
record['preserved_original_svg_sha256']=preserved
record['notes']=[
    'GaME tracked simple-knn build cache/object files were regenerated by native compilation; algorithm source files were not edited.',
    'Pip freeze is an audit record, not a standalone installer for Conda-only Faiss packages.',
    'Only small static installation tests; not complete Atlas AR/4D or a reconstruction benchmark.',
]
(out/'manifest.json').write_text(json.dumps(record,ensure_ascii=False,indent=2)+'\n')
print(out/'manifest.json')
