import gradio as gr
import torch
import os
import tempfile
import imageio
import glob
from omegaconf import OmegaConf
from PIL import Image
import numpy as np
from scipy.spatial.transform import Rotation as R
from scipy.interpolate import interp1d
from chunk_trajectory import slice_chunk_trajectory

from pose_control import (
    WanVideoGenerator,
    CAMERA_MOVEMENTS,
    seed_everything,
    CONFIG,
    preprocess_video_from_path,
    extrapolate_camera_path,
)


# -----------------------------------------------------------------
# 📁 Example Videos and Pose Caching
# -----------------------------------------------------------------

EXAMPLE_VIDEOS_DIR = "examples/videos"  # Directory containing example videos
POSE_CACHE_DIR = "examples/pose_cache"  # Directory to cache extracted poses
EXAMPLE_IMAGES_DIR = "examples/images"  # Directory containing example starting images


def get_example_videos():
    """Get list of example videos from the examples directory"""
    if not os.path.exists(EXAMPLE_VIDEOS_DIR):
        os.makedirs(EXAMPLE_VIDEOS_DIR, exist_ok=True)
        return []
    
    video_extensions = ['*.mp4', '*.avi', '*.mov', '*.mkv', '*.webm']
    videos = []
    for ext in video_extensions:
        videos.extend(glob.glob(os.path.join(EXAMPLE_VIDEOS_DIR, ext)))
    
    return sorted(videos)


def get_example_images():
    """
    Get example images from examples/images/ directory.
    Images can have .jpg, .jpeg, or .png extension.
    Prompts will be auto-generated by Qwen captioner when needed.
    
    Returns:
        list of tuples: [(image_path, name), ...]
    """
    examples = []
    
    if not os.path.exists(EXAMPLE_IMAGES_DIR):
        os.makedirs(EXAMPLE_IMAGES_DIR, exist_ok=True)
        return examples
    
    # Get all images
    image_extensions = ['*.jpg', '*.jpeg', '*.png']
    image_files = []
    for ext in image_extensions:
        image_files.extend(glob.glob(os.path.join(EXAMPLE_IMAGES_DIR, ext)))
    
    # Return image path and name (no prompts - Qwen will caption)
    for img_path in sorted(image_files):
        img_name = os.path.splitext(os.path.basename(img_path))[0]
        examples.append((img_path, img_name))
    
    return examples


def get_pose_cache_path(video_path):
    """Get the cache file path for a video's poses"""
    os.makedirs(POSE_CACHE_DIR, exist_ok=True)
    video_name = os.path.splitext(os.path.basename(video_path))[0]
    return os.path.join(POSE_CACHE_DIR, f"{video_name}_poses.npz")


def load_cached_poses(video_path):
    """Load cached poses if they exist"""
    cache_path = get_pose_cache_path(video_path)
    if os.path.exists(cache_path):
        print(f"📂 Loading cached poses from: {cache_path}")
        data = np.load(cache_path)
        poses = torch.from_numpy(data['poses'])
        intrinsics = torch.from_numpy(data['intrinsics'])
        return poses, intrinsics
    return None, None


def save_poses_to_cache(video_path, poses, intrinsics):
    """Save extracted poses to cache"""
    cache_path = get_pose_cache_path(video_path)
    print(f"💾 Saving poses to cache: {cache_path}")
    np.savez(cache_path, 
             poses=poses.cpu().numpy(), 
             intrinsics=intrinsics.cpu().numpy())


# -----------------------------------------------------------------
# 🎮 Pose Extension Strategies
# -----------------------------------------------------------------

def extend_poses_loop(poses, intrinsics, n_new_frames):
    """
    Loop/Tile: Repeat the pose sequence from the beginning.
    Good for cyclical movements like orbiting.
    """
    if n_new_frames <= 0:
        return poses, intrinsics
    
    print(f"🔄 Extending poses by LOOPING ({n_new_frames} new frames)...")
    
    N = poses.shape[1]
    poses_np = poses.cpu().numpy().squeeze(0)
    intrinsics_np = intrinsics.cpu().numpy().squeeze(0)
    
    # Calculate how many times we need to tile
    n_tiles = (n_new_frames // N) + 2
    tiled_poses = np.tile(poses_np, (n_tiles, 1, 1))
    tiled_intrinsics = np.tile(intrinsics_np, (n_tiles, 1, 1))
    
    # Take exactly what we need
    total_needed = N + n_new_frames
    extended_poses = tiled_poses[:total_needed]
    extended_intrinsics = tiled_intrinsics[:total_needed]
    
    return (torch.from_numpy(extended_poses).unsqueeze(0).to(poses.device, dtype=poses.dtype),
            torch.from_numpy(extended_intrinsics).unsqueeze(0).to(intrinsics.device, dtype=intrinsics.dtype))


def extend_poses_pingpong(poses, intrinsics, n_new_frames):
    """
    Ping-Pong/Mirror: Go forward then backward, creating a smooth back-and-forth motion.
    Good for movements that should reverse naturally.
    """
    if n_new_frames <= 0:
        return poses, intrinsics
    
    print(f"🔁 Extending poses by PING-PONG ({n_new_frames} new frames)...")
    
    N = poses.shape[1]
    poses_np = poses.cpu().numpy().squeeze(0)
    intrinsics_np = intrinsics.cpu().numpy().squeeze(0)
    
    # Create ping-pong sequence: forward + reversed (excluding endpoints to avoid duplicates)
    forward = poses_np
    backward = poses_np[-2:0:-1]  # Reverse, excluding first and last
    pingpong = np.concatenate([forward, backward], axis=0)
    
    forward_int = intrinsics_np
    backward_int = intrinsics_np[-2:0:-1]
    pingpong_int = np.concatenate([forward_int, backward_int], axis=0)
    
    # Tile the ping-pong sequence
    pingpong_len = len(pingpong)
    n_tiles = (n_new_frames // pingpong_len) + 2
    tiled_poses = np.tile(pingpong, (n_tiles, 1, 1))
    tiled_intrinsics = np.tile(pingpong_int, (n_tiles, 1, 1))
    
    # Take exactly what we need
    total_needed = N + n_new_frames
    extended_poses = tiled_poses[:total_needed]
    extended_intrinsics = tiled_intrinsics[:total_needed]
    
    return (torch.from_numpy(extended_poses).unsqueeze(0).to(poses.device, dtype=poses.dtype),
            torch.from_numpy(extended_intrinsics).unsqueeze(0).to(intrinsics.device, dtype=intrinsics.dtype))


def extend_poses_extrapolate(poses, intrinsics, n_new_frames, smoothing_window=10):
    """
    Extrapolate: Continue the motion based on recent velocity/angular velocity.
    Good for linear or smoothly curving movements.
    This is the original extrapolate_camera_path function.
    """
    return extrapolate_camera_path(poses, intrinsics, n_new_frames, smoothing_window)


def extend_poses_slowdown(poses, intrinsics, n_new_frames, decay_rate=0.95):
    """
    Slowdown/Decelerate: Continue motion but gradually slow down (never fully stops).
    The decay rate ensures motion continues but gets progressively slower.
    """
    if n_new_frames <= 0:
        return poses, intrinsics
    
    print(f"🐢 Extending poses with SLOWDOWN (decay={decay_rate}, {n_new_frames} new frames)...")
    
    N = poses.shape[1]
    window = min(10, N - 1)
    
    poses_np = poses.cpu().numpy().squeeze(0)
    intrinsics_np = intrinsics.cpu().numpy().squeeze(0)
    
    # Calculate average velocity from last few frames
    start_idx = N - window
    local_lin_vels = []
    local_ang_vels = []
    
    for i in range(start_idx, N - 1):
        P_curr = poses_np[i]
        P_next = poses_np[i+1]
        R_curr, t_curr = P_curr[:3, :3], P_curr[:3, 3]
        R_next, t_next = P_next[:3, :3], P_next[:3, 3]
        global_disp = t_next - t_curr
        local_vel = R_curr.T @ global_disp
        local_lin_vels.append(local_vel)
        R_diff = R_curr.T @ R_next
        rot_vec = R.from_matrix(R_diff).as_rotvec()
        local_ang_vels.append(rot_vec)
    
    avg_lin_vel = np.mean(np.stack(local_lin_vels), axis=0)
    avg_ang_vel = np.mean(np.stack(local_ang_vels), axis=0)
    
    new_poses = []
    last_pose = poses_np[-1]
    curr_R = last_pose[:3, :3]
    curr_t = last_pose[:3, 3]
    
    # Minimum velocity to ensure camera never fully stops
    min_vel_scale = 0.1  # Keep at least 10% of original velocity
    
    for frame_idx in range(n_new_frames):
        # Apply decaying velocity (but never go below minimum)
        decay_factor = max(decay_rate ** frame_idx, min_vel_scale)
        
        effective_lin_vel = avg_lin_vel * decay_factor
        effective_ang_vel = avg_ang_vel * decay_factor
        
        step_global = curr_R @ effective_lin_vel
        curr_t = curr_t + step_global
        
        R_rel_step = R.from_rotvec(effective_ang_vel)
        curr_R_obj = R.from_matrix(curr_R)
        curr_R = (curr_R_obj * R_rel_step).as_matrix()
        
        new_mat = np.eye(4)
        new_mat[:3, :3] = curr_R
        new_mat[:3, 3] = curr_t
        new_poses.append(new_mat)
    
    new_poses = np.stack(new_poses, axis=0)
    full_poses_np = np.concatenate([poses_np, new_poses], axis=0)
    
    last_intrin = intrinsics_np[-1:]
    new_intrinsics = np.repeat(last_intrin, n_new_frames, axis=0)
    full_intrinsics_np = np.concatenate([intrinsics_np, new_intrinsics], axis=0)
    
    return (torch.from_numpy(full_poses_np).unsqueeze(0).to(poses.device, dtype=poses.dtype),
            torch.from_numpy(full_intrinsics_np).unsqueeze(0).to(intrinsics.device, dtype=intrinsics.dtype))


def extend_poses_interpolate_stretch(poses, intrinsics, target_frames):
    """
    Interpolate/Stretch: Stretch or compress the trajectory to fit target frame count.
    Useful when you want to slow down or speed up the entire motion.
    """
    N = poses.shape[1]
    if target_frames == N:
        return poses, intrinsics
    
    print(f"📏 Stretching poses from {N} to {target_frames} frames via interpolation...")
    
    poses_np = poses.cpu().numpy().squeeze(0)
    intrinsics_np = intrinsics.cpu().numpy().squeeze(0)
    
    # Extract positions and rotations
    positions = poses_np[:, :3, 3]  # (N, 3)
    rotations = [R.from_matrix(poses_np[i, :3, :3]) for i in range(N)]
    quats = np.array([r.as_quat() for r in rotations])  # (N, 4)
    
    # Original and target time indices
    t_orig = np.linspace(0, 1, N)
    t_new = np.linspace(0, 1, target_frames)
    
    # Interpolate positions
    interp_pos = interp1d(t_orig, positions, axis=0, kind='cubic')
    new_positions = interp_pos(t_new)
    
    # Interpolate quaternions (simple linear for now, could use slerp)
    interp_quat = interp1d(t_orig, quats, axis=0, kind='linear')
    new_quats = interp_quat(t_new)
    # Normalize quaternions
    new_quats = new_quats / np.linalg.norm(new_quats, axis=1, keepdims=True)
    
    # Reconstruct poses
    new_poses = np.zeros((target_frames, 4, 4))
    for i in range(target_frames):
        new_poses[i, :3, :3] = R.from_quat(new_quats[i]).as_matrix()
        new_poses[i, :3, 3] = new_positions[i]
        new_poses[i, 3, 3] = 1.0
    
    # Interpolate intrinsics (usually just repeat, but interpolate for completeness)
    interp_intr = interp1d(t_orig, intrinsics_np, axis=0, kind='linear')
    new_intrinsics = interp_intr(t_new)
    
    return (torch.from_numpy(new_poses).unsqueeze(0).to(poses.device, dtype=poses.dtype),
            torch.from_numpy(new_intrinsics).unsqueeze(0).to(intrinsics.device, dtype=intrinsics.dtype))


# Map extension mode names to functions
POSE_EXTENSION_MODES = {
    "extrapolate": ("Extrapolate (Continue Motion)", extend_poses_extrapolate),
    "loop": ("Loop (Repeat Sequence)", extend_poses_loop),
    "pingpong": ("Ping-Pong (Back and Forth)", extend_poses_pingpong),
    "slowdown": ("Slowdown (Decelerate Gradually)", extend_poses_slowdown),
}


class VideoGenerationSession:
    def __init__(self):
        print("🚀 Initializing models...")
        self.config = OmegaConf.to_container(CONFIG, resolve=True)
        self.config = OmegaConf.create(self.config)
        self.temp_dir = tempfile.mkdtemp()
        self.config.experiment.output_root = self.temp_dir
        
        # Initialize generator and load models
        seed_everything(self.config.experiment.seed)
        self.generator = WanVideoGenerator(self.config)
        self.generator._init_captioner(is_vl=False)  # Start with text-only for T2I
        
        # Ensure chunk_poses is cleared
        self.config.camera_pose_control.chunk_poses = []
        
        print("⏳ Loading models...")
        self.generator._load_models()
        
        # State
        self.starting_image = None
        self.video_chunks = []
        self.chunk_movements = []
        self.chunk_captions = []  # Store captioned prompts for each chunk
        self.chunk_ctx_log = []  # Store context frames used for each chunk (for stitching)
        self.combined_video_path = None
        
        # State for extracted camera poses from reference video
        self.extracted_global_poses = None  # (1, N, 4, 4)
        self.extracted_global_intrinsics = None  # (1, N, 3, 3)
        self.reference_video_path = None
        self.extraction_mode_active = False  # Track if we're using extracted poses
        self.pose_extension_mode = "extrapolate"  # Default extension mode
        
        # Track the current global frame index for extracted poses
        self.extracted_pose_frame_index = 0
        
        print("✅ Models loaded successfully!")
    
    def generate_first_frame(self, prompt, negative_prompt):
        """Generate first frame using Wan2.1 (49 frames, take first)"""
        print("🎨 Generating first frame from prompt...")
        
        # Always ensure text-only captioner for T2V generation
        print("🔄 Initializing text-only captioner for T2V...")
        self.generator._init_captioner(is_vl=False)
        
        # Update config for first frame generation
        temp_config = OmegaConf.to_container(self.config, resolve=True)
        temp_config = OmegaConf.create(temp_config)
        temp_config.video_source.mode = "t2v"
        temp_config.video_source.prompt = prompt
        temp_config.video_source.t2v_length = 49  # Generate 49 frames
        temp_config.prompts.negative = negative_prompt
        
        # Temporarily update generator config
        old_config = self.generator.cfg
        self.generator.cfg = temp_config
        
        # Generate video
        video_path = self.generator.prepare_source_video()
        
        # Extract first frame
        reader = imageio.get_reader(video_path)
        first_frame = reader.get_data(0)
        reader.close()
        
        # Save as image
        first_frame_path = os.path.join(self.temp_dir, "first_frame.png")
        Image.fromarray(first_frame).save(first_frame_path)
        
        self.starting_image = first_frame_path
        
        # Restore config
        self.generator.cfg = old_config
        
        # Switch to VL captioner for subsequent chunk generation
        print("🔄 Switching to Vision-Language captioner for chunk generation...")
        self.generator._init_captioner(is_vl=True)
        
        print(f"✅ First frame generated: {first_frame_path}")
        return first_frame_path, "✅ First frame generated"
    
    def set_uploaded_image(self, image_path):
        """Set uploaded image as starting image"""
        if image_path is None:
            return None, "❌ No image uploaded"
        
        self.starting_image = image_path
        
        # Ensure VL captioner is loaded for uploaded images (need vision capabilities)
        print("🔄 Ensuring Vision-Language captioner is loaded for uploaded image...")
        self.generator._init_captioner(is_vl=True)
        
        return image_path, "✅ Uploaded image set as starting frame"
    
    def extract_camera_from_video(self, video_path, use_cache=True):
        """
        Extract camera poses from a reference video using TTT3R.
        Uses cached poses if available.
        """
        if video_path is None:
            return "❌ No video selected", ""
        
        print(f"🎥 Processing camera poses from: {video_path}")
        
        try:
            # Try to load from cache first
            if use_cache:
                cached_poses, cached_intrinsics = load_cached_poses(video_path)
                if cached_poses is not None:
                    self.extracted_global_poses = cached_poses.to(self.generator.device)
                    self.extracted_global_intrinsics = cached_intrinsics.to(self.generator.device)
                    self.reference_video_path = video_path
                    self.extraction_mode_active = True
                    self.extracted_pose_frame_index = 0
                    
                    num_frames = cached_poses.shape[1]
                    n_frames_per_chunk = self.config.inference_params.n_frames
                    ctx = self.config.inference_params.context_frames_2nd
                    
                    if num_frames <= n_frames_per_chunk:
                        max_chunks = 1
                    else:
                        max_chunks = 1 + (num_frames - n_frames_per_chunk) // (n_frames_per_chunk - ctx)
                    
                    status_msg = f"✅ Loaded cached camera poses!\n"
                    status_msg += f"📊 Total frames: {num_frames}\n"
                    status_msg += f"📹 Max chunks (without extension): ~{max_chunks}"
                    
                    info_msg = f"Reference: {os.path.basename(video_path)}\n"
                    info_msg += f"Frames: {num_frames} | Max chunks: {max_chunks}\n"
                    info_msg += f"💡 Using cached poses!"
                    
                    return status_msg, info_msg
            
            # Extract poses using TTT3R
            print(f"🔄 Extracting poses (no cache found)...")
            
            # Preprocess video
            full_vid = preprocess_video_from_path(
                video_path, 
                self.config.inference_params.height, 
                self.config.inference_params.width, 
                600  # Max frames
            ).unsqueeze(0).to(self.generator.device)
            
            print(f"📹 Video preprocessed: {full_vid.shape[1]} frames")
            
            # Extract poses using TTT3R
            with torch.no_grad():
                _, global_poses, global_intrinsics = self.generator.ttt3r.inference(full_vid)
            
            # Fix intrinsics principal point
            global_intrinsics[:, :, 0, -1] = self.config.inference_params.width / 2.0
            global_intrinsics[:, :, 1, -1] = self.config.inference_params.height / 2.0
            global_intrinsics = global_intrinsics.mean(dim=1, keepdim=True).repeat(
                1, global_poses.shape[1], 1, 1
            )
            
            # Save to cache
            save_poses_to_cache(video_path, global_poses, global_intrinsics)
            
            # Store extracted poses
            self.extracted_global_poses = global_poses.to(self.generator.device)
            self.extracted_global_intrinsics = global_intrinsics.to(self.generator.device)
            self.reference_video_path = video_path
            self.extraction_mode_active = True
            self.extracted_pose_frame_index = 0
            
            num_frames = global_poses.shape[1]
            
            # Calculate how many chunks can be generated without extension
            n_frames_per_chunk = self.config.inference_params.n_frames
            ctx = self.config.inference_params.context_frames_2nd
            
            if num_frames <= n_frames_per_chunk:
                max_chunks = 1
            else:
                max_chunks = 1 + (num_frames - n_frames_per_chunk) // (n_frames_per_chunk - ctx)
            
            # Visualize trajectory
            traj_path = os.path.join(self.generator.pm.dirs["visualizations"], "extracted_camera_trajectory.png")
            self.generator.pose_controller.visualize_trajectory(global_poses, traj_path)
            
            status_msg = f"✅ Camera poses extracted & cached!\n"
            status_msg += f"📊 Total frames: {num_frames}\n"
            status_msg += f"📹 Max chunks (without extension): ~{max_chunks}\n"
            status_msg += f"💾 Trajectory saved to: {traj_path}"
            
            info_msg = f"Reference: {os.path.basename(video_path)}\n"
            info_msg += f"Frames: {num_frames} | Max chunks: {max_chunks}\n"
            info_msg += f"💡 Poses cached for future use!"
            
            print(status_msg)
            return status_msg, info_msg
            
        except Exception as e:
            error_msg = f"❌ Failed to extract camera poses: {str(e)}"
            print(error_msg)
            import traceback
            traceback.print_exc()
            return error_msg, ""
    
    def clear_extracted_poses(self):
        """Clear the extracted camera poses and return to normal mode"""
        self.extracted_global_poses = None
        self.extracted_global_intrinsics = None
        self.reference_video_path = None
        self.extraction_mode_active = False
        self.extracted_pose_frame_index = 0
        return "✅ Extracted poses cleared. Select a new video.", ""
    
    def _extend_poses_if_needed(self, global_poses, global_intrinsics, total_frames_needed, speed_multiplier=1.0):
        """
        Extend poses if needed, using the selected extension mode.
        Also handles speed adjustment via interpolation.
        """
        current_frames = global_poses.shape[1]

        if speed_multiplier != 1.0:
            if speed_multiplier < 1.0:
                # Slow down: interpolate to more frames
                target_frames = int(current_frames / speed_multiplier)
                print(f"⏱️ Slowing down {speed_multiplier:.2f}x: {current_frames} → {target_frames} frames")
            else:
                # Speed up: subsample to fewer frames
                target_frames = int(current_frames / speed_multiplier)
                print(f"⏱️ Speeding up {speed_multiplier:.2f}x: {current_frames} → {target_frames} frames")
            
            global_poses, global_intrinsics = extend_poses_interpolate_stretch(
                global_poses, global_intrinsics, target_frames
            )
            current_frames = target_frames
        
        # Then extend if still not enough
        if total_frames_needed > current_frames:
            n_new_frames = total_frames_needed - current_frames + 10  # Add buffer
            
            mode = self.pose_extension_mode
            print(f"📐 Need {total_frames_needed} frames, have {current_frames}. Extending with mode: {mode}")
            
            if mode == "extrapolate":
                global_poses, global_intrinsics = extend_poses_extrapolate(
                    global_poses, global_intrinsics, n_new_frames
                )
            elif mode == "loop":
                global_poses, global_intrinsics = extend_poses_loop(
                    global_poses, global_intrinsics, n_new_frames
                )
            elif mode == "pingpong":
                global_poses, global_intrinsics = extend_poses_pingpong(
                    global_poses, global_intrinsics, n_new_frames
                )
            elif mode == "slowdown":
                global_poses, global_intrinsics = extend_poses_slowdown(
                    global_poses, global_intrinsics, n_new_frames
                )
            else:
                # Default to extrapolate
                global_poses, global_intrinsics = extend_poses_extrapolate(
                    global_poses, global_intrinsics, n_new_frames
                )
        
        return global_poses, global_intrinsics
    
    def _calculate_chunk_pose_end_frame(self, chunk_idx, context_frames_2nd):
        """
        Calculate the end frame index for poses needed by a chunk.
        
        The poses always start from frame 0 (full history needed).
        We only need to calculate the end frame.
        
        For chunk i:
        - Chunk 0: end = n_frames
        - Chunk i (i >= 1): end = n_frames + i * (n_frames - ctx)
        """
        n_frames = self.config.inference_params.n_frames
        
        if chunk_idx == 0:
            end_frame = n_frames
        else:
            end_frame = n_frames + chunk_idx * (n_frames - context_frames_2nd)
        
        return end_frame
    
    def generate_chunks_from_extracted(self, prompt, negative_prompt, num_chunks,
                                       context_frames_2nd, strength, num_gs_iterations, seed,
                                       extension_mode, speed_multiplier):
        """
        Generate chunks using the extracted camera poses from a reference video.
        """
        if self.starting_image is None:
            return None, "❌ Please set a starting image first (generate or upload)", "", ""
        
        if not self.extraction_mode_active or self.extracted_global_poses is None:
            return None, "❌ Please select and load a reference video first", "", ""
        
        # Update extension mode
        self.pose_extension_mode = extension_mode
        
        print(f"🎬 Generating {num_chunks} chunk(s) using extracted camera poses...")
        print(f"📐 Extension mode: {POSE_EXTENSION_MODES[extension_mode][0]}")
        print(f"⏱️ Speed multiplier: {speed_multiplier}x")
        
        # Update config
        self.config.video_source.prompt = prompt
        self.config.prompts.positive = prompt
        self.config.prompts.negative = negative_prompt
        self.config.inference_params.context_frames_2nd = context_frames_2nd
        self.config.inference_params.minxs = 1.0 - strength
        self.config.inference_params.num_gs_iterations = num_gs_iterations
        self.config.experiment.seed = seed
        
        # Set seed
        seed_everything(seed)
        
        # Calculate the maximum frame index needed (for the last chunk)
        last_chunk_idx = len(self.video_chunks) + num_chunks - 1
        total_frames_needed = self._calculate_chunk_pose_end_frame(last_chunk_idx, context_frames_2nd)
        
        # Get extended poses (apply speed multiplier and extension)
        global_poses = self.extracted_global_poses.clone()
        global_intrinsics = self.extracted_global_intrinsics.clone()
        
        global_poses, global_intrinsics = self._extend_poses_if_needed(
            global_poses, global_intrinsics, total_frames_needed, speed_multiplier
        )
        global_poses = global_poses.to(self.generator.device)
        global_intrinsics = global_intrinsics.to(self.generator.device)
        
        print(f"📊 Total frames available after extension: {global_poses.shape[1]}")
        print(f"📊 Total frames needed: {total_frames_needed}")
        
        # Generate requested number of chunks
        for chunk_iter in range(num_chunks):
            chunk_idx = len(self.video_chunks)
            is_first = (chunk_idx == 0)
            ctx = self.config.inference_params.context_frames if is_first else context_frames_2nd
            n_frames_per_chunk = self.config.inference_params.n_frames
            
            # Store context frames for stitching
            self.chunk_ctx_log.append(ctx)
            
            # Calculate end frame for this chunk (poses always start from 0)
            end_frame = self._calculate_chunk_pose_end_frame(chunk_idx, context_frames_2nd)
            
            # Ensure we don't exceed available frames
            if end_frame > global_poses.shape[1]:
                print(f"⚠️ Warning: end_frame {end_frame} exceeds available {global_poses.shape[1]}, clamping")
                end_frame = global_poses.shape[1]
            
            print(f"📍 Chunk {chunk_idx}: Using poses [0:{end_frame}] (ctx={ctx})")
            
            # Track movement type
            self.chunk_movements.append([f"EXTRACTED ({extension_mode})"])
            
            # Update loop params
            self.config.loop_params.n_chunks = len(self.chunk_movements)
            
            # Determine input video
            if chunk_idx == 0:
                input_video = self._image_to_video(self.starting_image)
            else:
                input_video = self.video_chunks[-1]
            
            chunk_poses, chunk_intrinsics = slice_chunk_trajectory(
                global_poses, global_intrinsics, chunk_idx, n_frames_per_chunk, ctx
            )
            # Generate chunk
            print(f"📹 Generating chunk {chunk_idx + 1}...")
            chunk_path = self.generator.run_inference_chunk(
                chunk_idx, input_video, chunk_poses, chunk_intrinsics,
                ctx, is_first, style_prompt=prompt, combined_video_path=self.combined_video_path
            )
            
            # Read caption generated by run_inference_chunk
            caption_file = os.path.join(self.generator.pm.dirs["captions"], f"chunk_{chunk_idx:03d}.txt")
            if os.path.exists(caption_file):
                with open(caption_file, "r") as f:
                    captioned_prompt = f.read()
                self.chunk_captions.append(captioned_prompt)
            else:
                self.chunk_captions.append(prompt)
            
            self.video_chunks.append(chunk_path)
            
            # Stitch all chunks
            self.combined_video_path = self._stitch_all()
        
        history = self._format_history()
        captions_display = self._format_captions()
        
        return self.combined_video_path, f"✅ Generated {num_chunks} chunk(s) from extracted poses", history, captions_display

    def generate_chunks(self, prompt, negative_prompt, selected_movements, 
                       num_chunks, context_frames_2nd, strength, num_gs_iterations, seed):
        """Generate multiple chunks with given camera movements"""
        if self.starting_image is None:
            return None, "❌ Please set a starting image first (generate or upload)", "", ""
        
        if not selected_movements or len(selected_movements) == 0:
            return None, "❌ Please select at least one camera movement", "", ""
        
        print(f"🎬 Generating {num_chunks} chunk(s)...")
        
        # Update config
        self.config.video_source.prompt = prompt
        self.config.prompts.positive = prompt
        self.config.prompts.negative = negative_prompt
        self.config.inference_params.context_frames_2nd = context_frames_2nd
        self.config.inference_params.minxs = 1.0 - strength
        self.config.inference_params.num_gs_iterations = num_gs_iterations
        self.config.experiment.seed = seed
        
        # Set seed
        seed_everything(seed)
        
        # Format movement for config
        if len(selected_movements) == 1:
            movement_config = selected_movements[0]
        else:
            movement_config = " + ".join(selected_movements)
        
        # Generate requested number of chunks
        for chunk_iter in range(num_chunks):
            self.config.camera_pose_control.chunk_poses.append(movement_config)
            self.chunk_movements.append(selected_movements.copy())
            
            self.config.loop_params.n_chunks = len(self.chunk_movements)
            
            if len(self.video_chunks) == 0:
                input_video = self._image_to_video(self.starting_image)
            else:
                input_video = self.video_chunks[-1]
            
            global_poses, global_intrinsics = self.generator._generate_controlled_poses()
            global_poses = global_poses.to(self.generator.device)
            global_intrinsics = global_intrinsics.to(self.generator.device)
            
            chunk_idx = len(self.video_chunks)
            is_first = (chunk_idx == 0)
            ctx = self.config.inference_params.context_frames if is_first else self.config.inference_params.context_frames_2nd
            
            # Store context frames for stitching
            self.chunk_ctx_log.append(ctx)
            
            chunk_poses, chunk_intrinsics = slice_chunk_trajectory(
                global_poses, global_intrinsics, chunk_idx,
                self.config.inference_params.n_frames, ctx
            )

            print(f"📹 Generating chunk {chunk_idx + 1}/{len(self.chunk_movements)}...")
            chunk_path = self.generator.run_inference_chunk(
                chunk_idx, input_video, chunk_poses, chunk_intrinsics,
                ctx, is_first, style_prompt=prompt, combined_video_path=self.combined_video_path
            )
            
            caption_file = os.path.join(self.generator.pm.dirs["captions"], f"chunk_{chunk_idx:03d}.txt")
            if os.path.exists(caption_file):
                with open(caption_file, "r") as f:
                    captioned_prompt = f.read()
                self.chunk_captions.append(captioned_prompt)
            else:
                self.chunk_captions.append(prompt)
            
            self.video_chunks.append(chunk_path)
            self.combined_video_path = self._stitch_all()
        
        history = self._format_history()
        captions_display = self._format_captions()
        
        return self.combined_video_path, f"✅ Generated {num_chunks} chunk(s)", history, captions_display
    
    def generate_custom_chunk(self, prompt, negative_prompt, roll, pitch, yaw,
                             move_forward, move_right, move_up,
                             ang_vel_roll, ang_vel_pitch, ang_vel_yaw,
                             num_chunks, context_frames_2nd, strength, num_gs_iterations, seed):
        """Generate chunk with custom parameters"""
        if self.starting_image is None:
            return None, "❌ Please set a starting image first", "", ""
        
        print(f"🎬 Generating {num_chunks} chunk(s) with custom movement...")
        
        self.config.video_source.prompt = prompt
        self.config.prompts.positive = prompt
        self.config.prompts.negative = negative_prompt
        self.config.inference_params.context_frames_2nd = context_frames_2nd
        self.config.inference_params.minxs = 1.0 - strength
        self.config.inference_params.num_gs_iterations = num_gs_iterations
        self.config.experiment.seed = seed
        
        seed_everything(seed)
        
        custom_movement = {
            "roll": roll, "pitch": pitch, "yaw": yaw,
            "move_forward": move_forward, "move_right": move_right, "move_up": move_up,
            "angular_velocity_roll": ang_vel_roll,
            "angular_velocity_pitch": ang_vel_pitch,
            "angular_velocity_yaw": ang_vel_yaw
        }
        
        for chunk_iter in range(num_chunks):
            self.config.camera_pose_control.chunk_poses.append(custom_movement)
            self.chunk_movements.append(["CUSTOM"])
            
            self.config.loop_params.n_chunks = len(self.chunk_movements)
            
            if len(self.video_chunks) == 0:
                input_video = self._image_to_video(self.starting_image)
            else:
                input_video = self.video_chunks[-1]
            
            global_poses, global_intrinsics = self.generator._generate_controlled_poses()
            global_poses = global_poses.to(self.generator.device)
            global_intrinsics = global_intrinsics.to(self.generator.device)
            
            chunk_idx = len(self.video_chunks)
            is_first = (chunk_idx == 0)
            ctx = self.config.inference_params.context_frames if is_first else self.config.inference_params.context_frames_2nd
            
            # Store context frames for stitching
            self.chunk_ctx_log.append(ctx)
            
            chunk_poses, chunk_intrinsics = slice_chunk_trajectory(
                global_poses, global_intrinsics, chunk_idx,
                self.config.inference_params.n_frames, ctx
            )
            
            print(f"📹 Generating custom chunk {chunk_idx + 1}/{len(self.chunk_movements)}...")
            chunk_path = self.generator.run_inference_chunk(
                chunk_idx, input_video, chunk_poses, chunk_intrinsics,
                ctx, is_first, style_prompt=prompt
            )
            
            caption_file = os.path.join(self.generator.pm.dirs["captions"], f"chunk_{chunk_idx:03d}.txt")
            if os.path.exists(caption_file):
                with open(caption_file, "r") as f:
                    captioned_prompt = f.read()
                self.chunk_captions.append(captioned_prompt)
            else:
                self.chunk_captions.append(prompt)
            
            self.video_chunks.append(chunk_path)
        
        self.combined_video_path = self._stitch_all()
        history = self._format_history()
        captions_display = self._format_captions()
        
        return self.combined_video_path, f"✅ Generated {num_chunks} custom chunk(s)", history, captions_display
    
    def _image_to_video(self, image_path, num_frames=None):
        """Convert image to video for first chunk"""
        img = Image.open(image_path)
        img = img.resize((self.config.inference_params.width, 
                         self.config.inference_params.height))
        frame = np.array(img)
        
        if num_frames is None:
            num_frames = self.config.inference_params.n_frames
        
        frames = [frame] * num_frames
        
        output_path = os.path.join(self.temp_dir, f"starting_video_{num_frames}f.mp4")
        imageio.mimsave(output_path, frames, fps=self.config.loop_params.output_fps)
        return output_path
    
    def _stitch_all(self):
        """Stitch all generated chunks"""
        if len(self.video_chunks) == 0:
            return None
        
        out_path = os.path.join(self.temp_dir, f"combined_{len(self.video_chunks)}.mp4")
        
        print(f"🎞️ Stitching {len(self.video_chunks)} chunks...")
        print(f"📊 chunk_ctx_log: {self.chunk_ctx_log}")
        
        total_frames = 0
        with imageio.get_writer(out_path, fps=self.config.loop_params.output_fps) as writer:
            for i, path in enumerate(self.video_chunks):
                reader = imageio.get_reader(path)
                chunk_frame_count = reader.count_frames()
                # Use stored context frames for this chunk (first chunk skips 0)
                skip = 0 if i == 0 else self.chunk_ctx_log[i]
                frames_written = 0
                for k, frame in enumerate(reader):
                    if k >= skip:
                        writer.append_data(frame)
                        frames_written += 1
                reader.close()
                print(f"  Chunk {i}: {chunk_frame_count} frames, skip={skip}, written={frames_written}")
                total_frames += frames_written
        
        print(f"✅ Combined video: {total_frames} total frames -> {out_path}")
        return out_path
    
    def _format_history(self):
        """Format generation history"""
        if len(self.chunk_movements) == 0:
            return "No chunks generated yet"
        
        history = []
        for i, movements in enumerate(self.chunk_movements):
            if movements == ["CUSTOM"]:
                history.append(f"Chunk {i+1}: CUSTOM")
            elif movements[0].startswith("EXTRACTED"):
                history.append(f"Chunk {i+1}: {movements[0]}")
            else:
                history.append(f"Chunk {i+1}: {' + '.join(movements)}")
        return "\n".join(history)
    
    def _format_captions(self):
        """Format captioned prompts for display"""
        if len(self.chunk_captions) == 0:
            return "No captions yet"
        
        captions = []
        for i, caption in enumerate(self.chunk_captions):
            captions.append(f"=== Chunk {i+1} ===")
            captions.append(caption)
            captions.append("")
        return "\n".join(captions)
    
    def reset(self):
        """Reset all state"""
        print("🔄 Resetting session...")
        self.starting_image = None
        self.video_chunks = []
        self.chunk_movements = []
        self.chunk_captions = []
        self.chunk_ctx_log = []  # Clear context log
        self.combined_video_path = None
        self.config.camera_pose_control.chunk_poses = []
        
        self.extracted_global_poses = None
        self.extracted_global_intrinsics = None
        self.reference_video_path = None
        self.extraction_mode_active = False
        self.pose_extension_mode = "extrapolate"
        self.extracted_pose_frame_index = 0
        
        print("🔄 Resetting captioner to text-only mode...")
        self.generator._init_captioner(is_vl=False)
        
        return None, None, "Reset complete", "", ""
    
    def rollback_to_chunk(self, chunk_number):
        """Rollback to a specific chunk, deleting all chunks after it"""
        if chunk_number < 1:
            return None, "❌ Invalid chunk number", "", ""
        
        if chunk_number > len(self.video_chunks):
            return self.combined_video_path, f"❌ Only {len(self.video_chunks)} chunks exist", self._format_history(), self._format_captions()
        
        self.video_chunks = self.video_chunks[:chunk_number]
        self.chunk_movements = self.chunk_movements[:chunk_number]
        self.chunk_captions = self.chunk_captions[:chunk_number]
        self.chunk_ctx_log = self.chunk_ctx_log[:chunk_number]  # Also rollback ctx_log
        self.config.camera_pose_control.chunk_poses = self.config.camera_pose_control.chunk_poses[:chunk_number]
        
        if len(self.video_chunks) > 0:
            self.combined_video_path = self._stitch_all()
        else:
            self.combined_video_path = None
        
        history = self._format_history()
        captions = self._format_captions()
        
        print(f"✂️ Rolled back to chunk {chunk_number}")
        return self.combined_video_path, f"✂️ Rolled back to chunk {chunk_number}", history, captions


# Initialize session on startup
print("="*60)
print("🎬 Pose-Controlled Video Generation")
print("="*60)
session = VideoGenerationSession()


# -----------------------------------------------------------------
# 🎛️ Gradio Interface Functions
# -----------------------------------------------------------------

def generate_first_frame_from_prompt(prompt, negative):
    image, status = session.generate_first_frame(prompt, negative)
    return image, status


def use_uploaded_image(image):
    if image is None:
        return None, "❌ No image uploaded"
    image_display, status = session.set_uploaded_image(image)
    return image_display, status


def generate_preset_chunks(prompt, negative, movements, num_chunks, ctx2, strength, gs_iter, seed):
    video, status, history, captions = session.generate_chunks(
        prompt, negative, movements, num_chunks, ctx2, strength, gs_iter, seed
    )
    return video, status, history, captions


def generate_custom_chunks(prompt, negative, roll, pitch, yaw, fwd, right, up, 
                           ang_r, ang_p, ang_y, num_chunks, ctx2, strength, gs_iter, seed):
    video, status, history, captions = session.generate_custom_chunk(
        prompt, negative, roll, pitch, yaw, fwd, right, up, ang_r, ang_p, ang_y,
        num_chunks, ctx2, strength, gs_iter, seed
    )
    return video, status, history, captions


def load_example_video_poses(video_path):
    """Load poses from selected example video"""
    if video_path is None:
        return "❌ No video selected", ""
    status, info = session.extract_camera_from_video(video_path, use_cache=True)
    return status, info


def clear_extracted_poses():
    """Clear the extracted poses"""
    status, info = session.clear_extracted_poses()
    return status, info


def generate_extracted_chunks(prompt, negative, num_chunks, ctx2, strength, gs_iter, seed,
                              extension_mode, speed_multiplier):
    """Generate chunks using extracted camera poses"""
    video, status, history, captions = session.generate_chunks_from_extracted(
        prompt, negative, num_chunks, ctx2, strength, gs_iter, seed,
        extension_mode, speed_multiplier
    )
    return video, status, history, captions


def on_example_image_select(evt: gr.SelectData, examples_data):
    """Handle example image selection - update display image and dropdown"""
    if examples_data is None or len(examples_data) == 0:
        return None, gr.update()
    
    selected_idx = evt.index
    if selected_idx < len(examples_data):
        img_path, name = examples_data[selected_idx]
        # Return: display image and dropdown selection (no prompt - Qwen will caption)
        return img_path, name
    return None, gr.update()


def on_example_dropdown_change(selected_name, examples_data):
    """Handle dropdown selection - update image display"""
    if selected_name is None or examples_data is None:
        return None
    
    for img_path, name in examples_data:
        if name == selected_name:
            return img_path
    return None


def use_example_image(selected_example_image):
    """Use the selected example image as starting image"""
    if selected_example_image is None:
        return None, "❌ No example image selected"
    image_display, status = session.set_uploaded_image(selected_example_image)
    return image_display, status


def reset_session():
    first_img, video, status, history, captions = session.reset()
    return first_img, video, status, history, captions, None, "", ""


def rollback_to_chunk(chunk_num):
    video, status, history, captions = session.rollback_to_chunk(chunk_num)
    return video, status, history, captions


def on_example_video_select(evt: gr.SelectData, gallery_data):
    """Handle example video selection from gallery - only preview, don't load poses"""
    if gallery_data is None or len(gallery_data) == 0:
        return None
    
    selected_idx = evt.index
    if selected_idx < len(gallery_data):
        video_path = gallery_data[selected_idx]
        return video_path
    return None


def toggle_camera_mode(mode):
    """Toggle visibility of camera mode groups"""
    return (
        gr.update(visible=(mode == "from_video")),  # from_video_group
        gr.update(visible=(mode == "preset")),       # preset_group
        gr.update(visible=(mode == "custom")),       # custom_group
    )


def generate_video(camera_mode, prompt, negative, num_chunks, ctx2, strength, gs_iter, seed,
                   # From video params
                   extension_mode, speed_multiplier,
                   # Preset params
                   movements,
                   # Custom params
                   roll, pitch, yaw, fwd, right, up, ang_r, ang_p, ang_y):
    """Unified generate function that dispatches based on camera mode"""
    
    if camera_mode == "from_video":
        return generate_extracted_chunks(
            prompt, negative, num_chunks, ctx2, strength, gs_iter, seed,
            extension_mode, speed_multiplier
        )
    elif camera_mode == "preset":
        return generate_preset_chunks(
            prompt, negative, movements, num_chunks, ctx2, strength, gs_iter, seed
        )
    elif camera_mode == "custom":
        return generate_custom_chunks(
            prompt, negative, roll, pitch, yaw, fwd, right, up, ang_r, ang_p, ang_y,
            num_chunks, ctx2, strength, gs_iter, seed
        )
    else:
        return None, "❌ Unknown camera mode", "", ""


# -----------------------------------------------------------------
# 🖼️ Build Gradio Interface
# -----------------------------------------------------------------

# Get example videos
example_videos = get_example_videos()
print(f"📁 Found {len(example_videos)} example videos in '{EXAMPLE_VIDEOS_DIR}'")

# Get example images (prompts will be auto-generated by Qwen)
example_images = get_example_images()
print(f"🖼️ Found {len(example_images)} example images")

with gr.Blocks(
    title="🎬 WorldWarp: Propagating 3D Geometry with Asynchronous Video Diffusion",
    css="""
        #main_generate_btn {
            background: linear-gradient(135deg, #667eea 0%, #764ba2 100%) !important;
            border: none !important;
            font-size: 1.1em !important;
            font-weight: bold !important;
            padding: 12px 24px !important;
            box-shadow: 0 4px 15px rgba(102, 126, 234, 0.4) !important;
            transition: all 0.3s ease !important;
        }
        #main_generate_btn:hover {
            transform: translateY(-2px) !important;
            box-shadow: 0 6px 20px rgba(102, 126, 234, 0.6) !important;
        }
    """
) as demo:
    gr.Markdown("# 🎬 WorldWarp: Propagating 3D Geometry with Asynchronous Video Diffusion")
    
    # Store example video paths for reference
    example_video_paths = gr.State(example_videos)
    
    # Store example images for reference (prompts auto-generated by Qwen)
    example_images_state = gr.State(example_images)
    
    with gr.Row():
        # =====================================================
        # COLUMN 1: Prompt & Starting Image
        # =====================================================
        with gr.Column(scale=1):
            gr.Markdown("### 📝 Prompt")
            
            # Example selection dropdown
            if len(example_images) > 0:
                example_names = [name for _, name in example_images]
                example_dropdown = gr.Dropdown(
                    choices=example_names,
                    label="📚 Select Example Image",
                    value=None,
                    interactive=True
                )
            else:
                example_dropdown = gr.Dropdown(
                    choices=[],
                    label="📚 Select Example (no examples found)",
                    value=None,
                    interactive=False
                )
            
            prompt = gr.Textbox(
                label="Prompt (leave empty for auto-caption)",
                lines=3,
                value="",
                placeholder="Optional: Enter a prompt or leave empty for Qwen to auto-generate"
            )
            negative = gr.Textbox(
                label="Negative Prompt",
                lines=2,
                value=CONFIG.prompts.negative
            )
            
            gr.Markdown("### 🖼️ Starting Image")
            
            with gr.Tab("📚 Examples"):
                if len(example_images) > 0:
                    example_images_gallery = gr.Gallery(
                        value=[(img_path, name) for img_path, name in example_images],
                        label="Example Images (click to select)",
                        columns=4,
                        rows=2,
                        height=180,
                        object_fit="cover",
                        allow_preview=True
                    )
                    selected_example_display = gr.Image(
                        label="Selected Example",
                        type="filepath",
                        height=160,
                        interactive=False
                    )
                    use_example_btn = gr.Button("✅ Use Selected Example", variant="primary")
                else:
                    example_images_gallery = None
                    selected_example_display = None
                    use_example_btn = None
                    gr.Markdown("*No example images found in `examples/images/`*")
            
            with gr.Tab("🎨 Generate"):
                gen_first_btn = gr.Button("Generate First Frame", variant="primary")
            
            with gr.Tab("📤 Upload"):
                uploaded_image = gr.Image(label="Upload Image", type="filepath", height=150)
                use_upload_btn = gr.Button("Use Uploaded Image", variant="primary")
            
            first_frame_display = gr.Image(label="Current Starting Image", type="filepath", height=200)
            first_frame_status = gr.Textbox(label="Status", interactive=False, max_lines=1)
        
        # =====================================================
        # COLUMN 2: Camera Movement & Parameters
        # =====================================================
        with gr.Column(scale=1):
            gr.Markdown("### 🎮 Camera Movement")
            
            # Camera mode selector
            camera_mode = gr.Radio(
                choices=[
                    ("📹 From Video", "from_video"),
                    ("🎯 Preset", "preset"),
                    ("🔧 Custom", "custom"),
                ],
                value="from_video",
                label="Control Mode"
            )
            
            # ----- From Video Options -----
            with gr.Group(visible=True) as from_video_group:
                if len(example_videos) > 0:
                    example_gallery = gr.Gallery(
                        value=[(v, os.path.basename(v)) for v in example_videos],
                        label="Example Videos (click to enlarge)",
                        columns=5,
                        rows=1,
                        height=80,
                        object_fit="cover",
                        allow_preview=True
                    )
                    
                    selected_video = gr.Video(
                        label="Selected Video",
                        height=200
                    )
                else:
                    example_gallery = None
                    selected_video = gr.Video(
                        label="Upload Reference Video",
                        sources=["upload"],
                        height=200
                    )
                
                with gr.Row():
                    load_poses_btn = gr.Button("🎯 Load Poses", variant="primary", size="sm")
                    clear_poses_btn = gr.Button("🗑️ Clear", variant="secondary", size="sm")
                
                extraction_status = gr.Textbox(label="Status", lines=2, interactive=False)
                extraction_info = gr.Textbox(label="Info", lines=1, interactive=False)
                
                with gr.Row():
                    extension_mode = gr.Radio(
                        choices=[
                            ("Extrapolate", "extrapolate"),
                            ("Loop", "loop"),
                            ("Ping-Pong", "pingpong"),
                            ("Slowdown", "slowdown"),
                        ],
                        value="extrapolate",
                        label="Extension Mode"
                    )
                
                speed_multiplier = gr.Slider(
                    minimum=0.25, maximum=4.0, value=1.0, step=0.25,
                    label="Speed Multiplier"
                )
            
            # ----- Preset Options -----
            with gr.Group(visible=False) as preset_group:
                movement_selector = gr.CheckboxGroup(
                    choices=sorted(list(CAMERA_MOVEMENTS.keys())),
                    label="Select Movements (can combine)",
                    value=[]
                )
            
            # ----- Custom Options -----
            with gr.Group(visible=False) as custom_group:
                gr.Markdown("**Rotation:**")
                with gr.Row():
                    roll = gr.Slider(-10, 10, 0, step=0.1, label="Roll")
                    pitch = gr.Slider(-10, 10, 0, step=0.1, label="Pitch")
                    yaw = gr.Slider(-10, 10, 0, step=0.1, label="Yaw")
                
                gr.Markdown("**Translation:**")
                with gr.Row():
                    fwd = gr.Slider(-0.05, 0.05, 0, step=0.001, label="Fwd")
                    right = gr.Slider(-0.05, 0.05, 0, step=0.001, label="Right")
                    up = gr.Slider(-0.05, 0.05, 0, step=0.001, label="Up")
                
                gr.Markdown("**Angular Velocity:**")
                with gr.Row():
                    ang_r = gr.Slider(-0.5, 0.5, 0, step=0.01, label="Roll")
                    ang_p = gr.Slider(-0.5, 0.5, 0, step=0.01, label="Pitch")
                    ang_y = gr.Slider(-0.5, 0.5, 0, step=0.01, label="Yaw")
            
            gr.Markdown("### ⚙️ Parameters")
            
            num_chunks = gr.Slider(1, 5, value=1, step=1, label="Number of Chunks")
            
            with gr.Row():
                context_frames_2nd = gr.Slider(1, 25, value=1, step=4, label="Context Frames")
                strength = gr.Slider(0.0, 1.0, value=0.6, step=0.05, label="Strength")
            
            with gr.Row():
                num_gs_iterations = gr.Slider(100, 2000, value=500, step=100, label="GS Iterations")
                seed = gr.Number(value=32, label="Seed", precision=0)
            
            gr.Markdown("### 🎬 Management")
            
            with gr.Row():
                rollback_chunk_num = gr.Number(value=1, label="Rollback to #", precision=0, minimum=1)
                rollback_btn = gr.Button("✂️ Rollback", variant="secondary", size="sm")
                reset_btn = gr.Button("🔄 Reset", variant="stop", size="sm")
        
        # =====================================================
        # COLUMN 3: Output
        # =====================================================
        with gr.Column(scale=1.25):
            gr.Markdown("### 🎥 Output")
            
            video_output = gr.Video(label="Generated Video", height=400)
            
            gen_btn = gr.Button(
                "🎬 Generate Video",
                variant="primary",
                size="lg",
                elem_id="main_generate_btn"
            )
            
            generation_status = gr.Textbox(label="Status", interactive=False, max_lines=2)
            
            gr.Markdown("### 📜 History")
            history_text = gr.Textbox(
                label="Chunks",
                lines=4,
                interactive=False,
                value="No chunks yet"
            )
            
            gr.Markdown("### 💬 Captions")
            captions_text = gr.Textbox(
                label="Prompts",
                lines=6,
                interactive=False,
                value="No captions yet"
            )
    
    # =====================================================
    # EVENT HANDLERS
    # =====================================================
    
    # Camera mode toggle - show/hide relevant options
    camera_mode.change(
        toggle_camera_mode,
        [camera_mode],
        [from_video_group, preset_group, custom_group]
    )
    
    # Example image selection events
    if example_images_gallery is not None:
        # Gallery click -> update dropdown and selected example display
        example_images_gallery.select(
            on_example_image_select,
            [example_images_state],
            [selected_example_display, example_dropdown]
        )
        
        # Use example button -> set as starting image
        use_example_btn.click(
            use_example_image,
            [selected_example_display],
            [first_frame_display, first_frame_status]
        )
    
    # Dropdown change -> update selected example display
    example_dropdown.change(
        on_example_dropdown_change,
        [example_dropdown, example_images_state],
        [selected_example_display]
    )
    
    # Starting image events
    gen_first_btn.click(
        generate_first_frame_from_prompt,
        [prompt, negative],
        [first_frame_display, first_frame_status]
    )
    
    use_upload_btn.click(
        use_uploaded_image,
        [uploaded_image],
        [first_frame_display, first_frame_status]
    )
    
    # Example video gallery selection - only preview, don't load poses
    if example_gallery is not None:
        example_gallery.select(
            on_example_video_select,
            [example_video_paths],
            [selected_video]  # Only update video preview
        )
    
    # Pose loading events
    load_poses_btn.click(
        load_example_video_poses,
        [selected_video],
        [extraction_status, extraction_info]
    )
    
    clear_poses_btn.click(
        clear_extracted_poses,
        [],
        [extraction_status, extraction_info]
    )
    
    # Main generate button - unified handler
    gen_btn.click(
        generate_video,
        [camera_mode, prompt, negative, num_chunks, context_frames_2nd, 
         strength, num_gs_iterations, seed,
         # From video params
         extension_mode, speed_multiplier,
         # Preset params
         movement_selector,
         # Custom params
         roll, pitch, yaw, fwd, right, up, ang_r, ang_p, ang_y],
        [video_output, generation_status, history_text, captions_text]
    )
    
    # Management events
    reset_btn.click(
        reset_session,
        None,
        [first_frame_display, video_output, generation_status, history_text, captions_text,
         selected_video, extraction_status, extraction_info]
    )
    
    rollback_btn.click(
        rollback_to_chunk,
        [rollback_chunk_num],
        [video_output, generation_status, history_text, captions_text]
    )


if __name__ == "__main__":
    server_port = int(os.environ.get("GRADIO_SERVER_PORT", "7890"))
    print("\n🌐 Starting Gradio interface...")
    print(f"📁 Example videos directory: {EXAMPLE_VIDEOS_DIR}")
    print(f"🖼️ Example images directory: {EXAMPLE_IMAGES_DIR}")
    print(f"💾 Pose cache directory: {POSE_CACHE_DIR}")
    print("💡 Prompts will be auto-generated by Qwen captioner")
    print(f"Access at: http://localhost:{server_port}")
    print("="*60)
    demo.launch(server_name="0.0.0.0", server_port=server_port)
